#!/usr/bin/env sh

sxhkd &

. "${HOME}/.cache/wal/colors.sh"

# colors

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"

bspc monitor -d dev web term media files docs misc

bspc config click_to_focus button1
bspc config pointer_modifier mod4
bspc config pointer_action1 move

bspc config border_width 1
bspc config window_gap 5 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# desktop configuration
bspc desktop dev --layout monocle
bspc desktop web --layout monocle

# applications configuration
bspc rule -a GoldenDict desktop='^6'
bspc rule -a Cantata desktop='^6'
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Kicad state=floating

xsetroot -cursor_name left_ptr

feh --bg-scale ~/.config/bspwm/wallpaper.jpg

$HOME/.config/polybar/launch.sh

